name: Deploy to cPanel

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Create Express .env file
      run: |
        echo "# MongoDB Atlas Connection" > .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "MONGODB_DB=FreshShareDB" >> .env
        echo "PORT=3001" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "FASTIFY_BACKEND_URL=http://localhost:8080" >> .env
        
        # Handle BASE_URL special case for root deployment
        BASE_URL="${{ secrets.BASE_URL }}"
        if [ "$BASE_URL" = " " ]; then
          BASE_URL=""
        fi
        echo "BASE_URL=$BASE_URL" >> .env
        
        echo "NODE_ENV=production" >> .env
        echo "USDA_API_KEY=${{ secrets.USDA_API_KEY }}" >> .env

    - name: Create Fastify .env file
      run: |
        mkdir -p fastify-backend
        echo "PORT=8080" > fastify-backend/.env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> fastify-backend/.env
        echo "NODE_ENV=production" >> fastify-backend/.env

    - name: Install dependencies
      run: npm install

    - name: Deploy to cPanel
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/public_html/
          mkdir -p freshshare
          cd freshshare
          
          # Clear previous files but keep node_modules
          find . -mindepth 1 -maxdepth 1 -not -name "node_modules" -exec rm -rf {} \;
